baseURL = 'sycx902.github.io'
languageCode = 'en-us'
title = '902 Rooms'
theme = "mana"


[params]
  description = """Random journal experience,
  Arbitrary variable. """
  favicon = "/favicon/favicon.ico"
  footerText = "Built with Hugo and Mana theme"  # Optional

  # Hero section title (optional - defaults to site.Title)
  heroTitleLine1 = "Personal Blog"  # First line of hero title
  heroTitleLine2 = "Juna"    # Second line of hero title (optional)


 [params.avatar]
  url = "static/images/orange.jpg"
  # url = "https://res.cloudinary.com/dzbcjm3ar/image/upload/v1728524523/902/902.gif"



 [params.buyMeACoffee]
  enabled = true
  id = "yourwidgetid"
  description = "Support me on Buy me a coffee!"
  message = ""  # Optional message
  color = "#BD5FFF"  # Widget color
  position = "Right"  # "Left" or "Right"
  x_margin = "18"  # Horizontal margin in pixels
  y_margin = "18"  # Vertical margin in pixels


 [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20

[[menus.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 30

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 40
